# Generated by Django 6.0 on 2026-01-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixe_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('Loyer', models.IntegerField()),
                ('Auto_Assurance', models.IntegerField()),
                ('Habitation_Assurance', models.IntegerField()),
                ('Internet', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Variables_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('Nourriture', models.FloatField()),
                ('Autres', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
