# Generated by Django 6.0 on 2026-01-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_fixe_expenses_variables_expenses_delete_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('Loyer', models.IntegerField(blank=True, null=True)),
                ('Auto_Assurance', models.IntegerField(blank=True, null=True)),
                ('Habitation_Assurance', models.IntegerField(blank=True, null=True)),
                ('Internet', models.FloatField(blank=True, null=True)),
                ('Nourriture', models.FloatField(blank=True, null=True)),
                ('Autres', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Fixe_Expenses',
        ),
        migrations.DeleteModel(
            name='Variables_Expenses',
        ),
    ]
