# Generated by Django 6.0 on 2026-01-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_depenses_delete_fixe_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenses',
            name='Autres_commentaires',
            field=models.TextField(blank=True, help_text="Commentaires sur la dépense 'Autres'", null=True),
        ),
        migrations.AlterField(
            model_name='depenses',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
