# Generated by Django 6.0 on 2026-01-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_depenses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depenses',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
