# Generated by Django 6.0 on 2026-01-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_depenses_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autres_Depenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('Fairstone', models.FloatField(blank=True, null=True)),
                ('REER_CELI', models.FloatField(blank=True, null=True)),
                ('Sol_Juline', models.FloatField(blank=True, null=True)),
                ('Assurance_Collective', models.FloatField(blank=True, null=True)),
                ('Frais_utilisisation', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('Zaro_Revenue', models.FloatField(blank=True, null=True)),
                ('Juline_Revenue', models.FloatField(blank=True, null=True)),
                ('Don', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='depenses',
            name='Autres_commentaires',
        ),
        migrations.AddField(
            model_name='depenses',
            name='Commentaires',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depenses',
            name='Don',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depenses',
            name='Fairstone',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depenses',
            name='Juline_family',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depenses',
            name='Loisir',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depenses',
            name='NetFlix',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depenses',
            name='Scolarite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depenses',
            name='Tel_Juline',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depenses',
            name='Tel_Zaro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depenses',
            name='Zaro_mom',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
