# Generated by Django 6.0 on 2026-01-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_autres_depenses_revenue_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autres_Depenses',
            new_name='AutresDepenses',
        ),
    ]
