# Generated by Django 6.0 on 2026-01-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_rename_autres_depenses_autresdepenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenses',
            name='Burnie_frais',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depenses',
            name='Electricite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depenses',
            name='Essence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
