# Generated by Django 6.0 on 2026-02-02 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_depenses_burnie_frais_depenses_electricite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depenses',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
