# Generated by Django 6.0 on 2026-02-02 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_depenses_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='autresdepenses',
            name='Commentaires',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autresdepenses',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
